{% set name = "imlib" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/imlib-{{ version }}.tar.gz
  sha256: 034f1ac343afcdc1dab12a88d9ed79490815c9c9d1e0e673f56e7cc61f70a9ee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - configobj
    - micrometa
    - natsort
    - pandas
    - psutil
    - python >={{ python_min }}
    - pyyaml
    - scikit-image
    - scipy
    - seaborn
    - slurmio
    - tqdm

test:
  imports:
    - imlib
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/adamltyson/imlib
  summary: General data processing functions
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - adamltyson
    - goanpeca
